### ISSUE TITLE
Reconfigure docker files

### ISSUE THREAD

**Issue by vse3211** [vse3211/factorio-helper-online#5]
Move container to alpine linux
Configure compose file & update app container

**Comment by d3adwolf** [comment]
Compose уже есть:
```
fhw:
    image: ghcr.io/vse3211/fhw:latest
    container_name: fhw
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Almaty
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=25568804
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DOTNET_RUNNING_IN_CONTAINER=true
      - INDOCKER=1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/https/:/https/
      - /root/factorio/:/app/wwwroot/factorio/
    restart: always
```
